hotel/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('system.urls')),
    path('accounts/', include('allauth.urls')),
]

system/urls.py
from django.urls import path
from . import views
from django.views.decorators.cache import never_cache
from django.conf.urls.static import static
from django.conf import settings

app_name='system'
urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('room_list/', views.RoomListView, name='RoomList'),
    path('explore/<category>', views.Explore, name='explore'),
    path('booking_list/', views.BookingList, name='BookingList'),
    path('book/<category>', views.BookingView.as_view(), name='BookingView'),
    path('booking/cancel/<pk>', views.CancelBookingView.as_view(), name='CancelBookingView'),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


system/models.py
import datetime
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils import timezone
# Create your models here.
# from django.db.models.constraints import CheckConstraint

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

class Cat(models.Model):
    category = models.CharField(primary_key=True, max_length=100)
    description = models.TextField()
    category_picture = models.ImageField(upload_to = 'cat', null=True, blank=True)
    actual_price_range = models.CharField(max_length=100)
    offer_price_range = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.category}'

class Room(models.Model):
    room_category = models.ForeignKey(Cat, on_delete=models.CASCADE)
    number = models.IntegerField(unique=True)
    people = models.IntegerField()
    picture = models.ImageField(upload_to = 'room/', null=True, blank=True)
    actual_price = models.IntegerField()
    offer_price = models.IntegerField()

    def __str__(self):
        # return '%d : %s with People : %d' % (self.number, self.room_category, self.people)
        return 'Room with People - %d' %self.people
    
    # def clean(self, *args, **kwargs):
    #     if self.actual_price <= self.offer_price:
    #         raise ValidationError('offer price should be lower than the actual price')
    #     return super().clean(*args, **kwargs)
    
    def clean(self, *args, **kwargs):
        if self.offer_price <= 0:
            raise ValidationError('Price should be greater than Zero')
        elif self.actual_price <= self.offer_price:
            raise ValidationError('offer price should be lower than the actual price')
        return super().clean(*args, **kwargs)


# def clean_image(self):
#         IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']
#         uploaded_image = self.cleaned_data.get("image",  False)
#         extension = str(uploaded_image).split('.')[-1]
#         file_type = extension.lower()
#         if not uploaded_image:       
#             raise ValidationError("please upload an Image") # handle empty image

#         if file_type not in IMAGE_FILE_TYPES:
#             raise ValidationError("File is not image.")
#         return uploaded_image

#     def clean(self):
#         cleaned_data = super().clean()
#         first_name = cleaned_data.get('first_name')
#         last_name  = cleaned_data.get('last_name')
#         if first_name == last_name:
#             raise ValidationError( "First name and last name cannot be the same." )



class Booking(models.Model):
    user=models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    room=models.ForeignKey(Room, on_delete=models.CASCADE)
    check_in=models.DateTimeField()
    check_out=models.DateTimeField()
    payment_status_choices = {
        ('SUCCESS', 'SUCCESS'),
        ('FAILURE', 'FAILURE'),
        ('PENDING', 'PENDING')}
    payment_status = models.CharField(max_length=10, choices=payment_status_choices, default='PENDING')
    amount = models.FloatField()
    order_id = models.CharField(unique=True, max_length=100, null=True, blank=True, default=None)
    datetime_of_payment = models.DateTimeField(default=timezone.now)
    # After payment
    razorpay_order_id = models.CharField(max_length=500, null=True, blank=True)
    razorpay_payment_id = models.CharField(max_length=500, null=True, blank=True)
    razorpay_signature = models.CharField(max_length=500, null=True, blank=True)
    
    
    def save(self, *args, **kwargs):
        if self.order_id is None and self.datetime_of_payment and self.id:
            self.order_id = self.datetime_of_payment.strftime('GLUG%Y%m%dODR') + str(self.id)
        return super().save(*args, **kwargs)
        
    
    def __str__(self):
        # return f'{self.room} from {self.check_in} to {self.check_out}.'
        return f'{self.room}'
    
    def can_be_booked(self):
        now=timezone.now()
        if now + datetime.timedelta(days=1)<=self.check_in:
            return self.room


    # def get_room_category(self):
    #     room_categories=dict(self.room.category)
    #     room_category=room_categories.get(self.room.category)
    #     return room_category
    
    def get_cancel_booking_url(self):
        return reverse('system:CancelBookingView', args=[self.pk])

    def get_absolute_url(self):
        return reverse('system:BookingList',)

system/forms.py
from django import forms
from .models import Room, Booking, Cat
# from .views import check_availability

from django.core import validators
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

class AvailabilityForm(forms.Form):
    category = forms.CharField(max_length=100)
    check_in = forms.DateTimeField(input_formats='%Y-%m-%dT%H:%M', required=True)
    check_out = forms.DateTimeField(input_formats='%Y-%m-%dT%H:%M', required=True)
    people = forms.IntegerField(required=True)

# validators=[validate_book],
# def validate_book(self, value):
#     if value % 2 != 0:
#         raise ValidationError(
#             _('%(value)s No room is available in the given duration'),
#             params={'value': value},
#          )


    # def clean(self):
    #     cleaned_data = super().clean()
    #     room_list = Room.objects.filter(room_category=cleaned_data.get('category'), people=cleaned_data.get('people'))
    #     available_rooms = []
    #     for room in room_list:
    #         if check_availability(room, cleaned_data.get('check_in'), cleaned_data.get('check_out')):
    #             available_rooms.append(room)
    #     if len(available_rooms) == 0:
    #         raise ValidationError("No room is available in the given duration")
    #     # return super().clean()

    # def clean(self):
    #     super(AvailabilityForm, self).clean()
    #     room_list = Room.objects.filter(room_category=self.cleaned_data.get('category'), people=self.cleaned_data.get('people'))
    #     available_rooms = []
    #     for room in room_list:
    #         if check_availability(room, self.cleaned_data.get('check_in'), self.cleaned_data.get('check_out')):
    #             available_rooms.append(room)
    #     if len(available_rooms) == 0:
    #         self.errors['check_in'] = self.error_class(['No room is available in the given duration'])
    #         raise ValidationError("No room is available in the given duration")
    #     return self.cleaned_data

def check_availability(room, check_in, check_out):
    avail_list=[]
    booking_list=Booking.objects.filter(room=room)
    for booking in booking_list:
        if booking.check_in > check_out or booking.check_out < check_in:
            avail_list.append(True)
        else:
            avail_list.append(False)
    return all(avail_list)

system/views.py
from django.views.decorators.cache import never_cache
from django.shortcuts import get_object_or_404, render, redirect, Http404
from django.http import HttpResponseRedirect, HttpResponse
from django.views import generic
from django.urls import reverse, reverse_lazy
from .models import Booking, Room, Cat
from .forms import AvailabilityForm
from django.contrib.auth.decorators import login_required
import datetime
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt
from django.contrib.sites.shortcuts import get_current_site
# Payment
from hotel import settings
import razorpay
razorpay_client = razorpay.Client(auth=(settings.razorpay_id, settings.razorpay_account_id))
razorpay_client.set_app_details({"title" : "Django", "version" : "3.2.3"})

# Create your views here.
@never_cache
def homepage(request):
    return render(request, 'system/index.html')


@login_required
def RoomListView(request):
    # cat_room_list=[]
    # for i in range(0,7):
    #     cat_room_list.append(Cat.objects.all()[i])
    # # print(cat_room_list)
    cat_room_list=Cat.objects.all()
    cat_list = []
    for cat in cat_room_list:
        # print(cat)
        cat_url = reverse('system:explore', kwargs={'category':cat}) # args=[cat]
        print('URL=', cat_url)
        cat_list.append((cat,cat_url))
    context = {'cat_list':cat_list,}
    return render(request, 'system/room_list.html', context)
    # room=Room.objects.all()[0]
    # room_categories=dict(room.categories)
    # room_values=room_categories.values()
    # room_list=[]
    # for room_category in room_categories:
    #     room=room_categories.get(room_category)
    #     room_url=reverse('system:BookingView', kwargs={'category':room_category})
    #     room_list.append((room, room_url))
    # context={
    #     'room_list':room_list,
    # }
    # return render(request, 'system/room_list.html', context)

def Explore(request, *args, **kwargs):
    category=kwargs.get('category')
    print(category)
    # form=AvailabilityForm()
    room_list=Room.objects.filter(room_category=category)
    print(room_list)
    cat1 = Cat.objects.get(category=category)
    # To check availabile room
    booked=[]
    avail=[]
    temp=[]
    for room in room_list:
        bookings = Booking.objects.filter(room=room)
        print("booking=",bookings)
        avail.append(room)
        for book in bookings:
            # For removeing old checkout booking
            now=timezone.now()
            if now + datetime.timedelta(days=1)<book.check_out:
            # ----
                print('Book =', book)
                a = book.can_be_booked()
                if a == None:
                    temp.append(book)
                else:
                    booked.append(book)
    if request.method == 'POST':
        form=AvailabilityForm(request.POST)
        if form.is_valid():
            data=form.cleaned_data
        else:
            return render(request, 'system/explore.html', {'category':category, 'cat':cat1, 'room_list':room_list, 'form':form,})
        form_room_list = Room.objects.filter(room_category=category, people=data['people'])
        print(form_room_list)
        available_rooms = []
        for room in form_room_list:
            if check_availability(room, data['check_in'], data['check_out']):
                available_rooms.append(room)
        if len(available_rooms) > 0:
            room = available_rooms[0]
            booking = Booking.objects.create(
                user=request.user, room=room, check_in=data['check_in'], check_out=data['check_out'], amount=100
            )
            booking.save()
            return HttpResponseRedirect(reverse_lazy('system:BookingList'))
        else:
            print('-- NO Rooms are avaliable --')
            # return HttpResponseRedirect(reverse('system:explore', kwargs={'category':cat1, 'msg':'error'}))
            form=AvailabilityForm()
            context={'message':'message', 'category':category, 'cat':cat1, 'room_list':room_list, 'form':form, 'avail':avail, 'temp':temp, 'booked':booked}
            return render(request, 'system/explore.html', context)
    else:
        form=AvailabilityForm()
    context={'category':category, 'cat':cat1, 'room_list':room_list, 'form':form, 'avail':avail, 'temp':temp, 'booked':booked}
    return render(request, 'system/explore.html', context)
# class Explore(generic.View):
#     def get(self, request, *args, **kwargs):
#         category=self.kwargs.get('category', None)
#         form=AvailabilityForm()
#         room_list=Room.objects.filter(room_category=category)
#         print(room_list)
#         cat = Cat.objects.get(category=category)
#         # To check availabile room
#         booked=[]
#         avail=[]
#         temp=[]
#         for room in room_list:
#             bookings = Booking.objects.filter(room=room)
#             print("booking=",bookings)
#             if len(bookings) == 0:
#                 avail.append(room)
#             else:
#                 for book in bookings:
#                     # For removeing old checkout booking
#                     now=timezone.now()
#                     if now + datetime.timedelta(days=1)<book.check_out:
#                     # ----
#                         print(book)
#                         a = book.can_be_booked()
#                         if a == None:
#                             temp.append(book)
#                         else:
#                             booked.append(book)
                    
#         context={'category':category, 'cat':cat, 'room_list':room_list, 'avail':avail, 'temp':temp, 'booked':booked}
#         return render(request, 'system/explore.html', context)

#     def post(self, request, *args, **kwargs):
#         category = self.kwargs.get('category', None)
#         form=AvailabilityForm(request.POST)
#         if form.is_valid():
#             data=form.cleaned_data
#         else:
#             return HttpResponseRedirect(reverse('system:explore'))
#         room_list = Room.objects.filter(room_category=category, people=data['people'])
#         print(room_list)
#         available_rooms = []
#         for room in room_list:
#             if check_availability(room, data['check_in'], data['check_out']):
#                 available_rooms.append(room)
#         if len(available_rooms) > 0:
#             room = available_rooms[0]
#             print(category)
#             # To get room amount
#             # amt = Room.objects.all()[0]
#             # amt_categories = dict(amt.categories_amount)
#             # tamount = amt_categories.get(category)
#             booking = Booking.objects.create(
#                 user=self.request.user, room=room, check_in=data['check_in'], check_out=data['check_out'], amount=100
#             )
#             booking.save()
#             return HttpResponseRedirect(reverse('system:BookingList'))
#         else:
#             return HttpResponse('<h1>Sorry ! This room is not available.</h1><br><h2>Try booking another one.</h2>')


"""
class BookingView(generic.FormView):
    form_class = AvailabilityForm
    template_name = 'system/book.html'
    success_url = 'system:BookingList'

    def form_valid(self, form):
        data=form.cleaned_data
        room_list=Room.objects.filter(category=data['room_category'])
        available_rooms=[]
        for room in room_list:
            if check_availability(room, data['check_in'], data['check_out']):
                available_rooms.append(room)
        if len(available_rooms)>0:
            room=available_rooms[0]
            booking=Booking.objects.create(
                user=self.request.user, room=room, check_in=data['check_in'], check_out=data['check_out']
            )
            booking.save()
            return HttpResponse(booking)
        else:
            return HttpResponse('This category of rooms are booked.')
"""

# Not using
class BookingView(generic.View):
    def get(self, request, *args, **kwargs):
        category=self.kwargs.get('category', None)
        form=AvailabilityForm()
        room_list=Room.objects.filter(room_category=category)
        print(room_list)
        cat = Cat.objects.get(category=category)
        context={'cat':cat, 'room_list':room_list,}
        return render(request, 'system/book.html', context)
        # category=self.kwargs.get('category', None)
        # form=AvailabilityForm()
        # room_list=Room.objects.filter(room_category=category)
        # if len(room_list)>0:
        #     room=room_list[0]
        #     room_category=dict(room.categories).get(room.category, None)
        #     print(room_category)
        #     context = {
        #         'room_category': room_category,
        #         'form':form,
        #     }
        #     return render(request, 'system/book.html', context)
        # else:
        #     return HttpResponse('Category does not exit !')

    def post(self, request, *args, **kwargs):
        category = self.kwargs.get('category', None)
        form=AvailabilityForm(request.POST)
        if form.is_valid():
            data=form.cleaned_data
        else:
            return HttpResponseRedirect(reverse('system:explore'))
        print('CATEGORY=', data['category'])
        room_list = Room.objects.filter(room_category=category, people=data['people'])
        print(room_list)
        available_rooms = []
        for room in room_list:
            if check_availability(room, data['check_in'], data['check_out']):
                available_rooms.append(room)
        if len(available_rooms) > 0:
            room = available_rooms[0]
            print(category)
            # To get room amount
            # amt = Room.objects.all()[0]

system/templates/system/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block tittle %} {% endblock %}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
  <script src="https://kit.fontawesome.com/dbed6b6114.js" crossorigin="anonymous"></script>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;500;600;700;800;900&display=swap');

    :root{
      --transition: all 0.7s ease;
      --yellow: #17dcff;
      --dark: #292826;
    }
    *{
        box-sizing: border-box;
        padding: 0;
        margin: 0;
        font-family: 'Playfair Display', serif;
    }
    html{
        scroll-behavior: smooth;
    }
    .btn1{
        font-size: 16px;
        text-transform: uppercase;
        font-weight: 600;
        border: none;
        border-radius: 5px;
        padding: 10px;
        width: 140px;
        display: block;
        margin: 15px auto;
        cursor: pointer;
        transition: var(--transition);
    }
    .btn1:hover{
        opacity: 0.85;
    }
    .flex{
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
    }
    @media(max-width: 500px){
        body{
            font-size: 14px;
        }
    }

    /* header */
    .header{
        color: #fff;
        padding: 25px;
        display: flex;
        flex-direction: column;
        align-content: stretch;
    }
    .head-top{
      margin-top: 18px;
      display: flex;
      justify-content: space-between;
      align-items: center;
    }
    .head-top span{
      /* font-family: "Poppins", sans-serif; */
      margin-left: 45px;
      margin-right: 25px;
      cursor: pointer;
      font-size: 22px;
      padding: 8px 20px;
      border: 1px solid white;
      letter-spacing: 2px;
      transition: var(--transition);
    }
    .head-top span:hover{
      color: var(--yellow);
    }
    @media(max-width: 500px){
        .head-btn{
            font-size: 17px;
        }
        .head-top span{
          font-size: medium;
          margin: auto;
      }
    }

    /* side nav */
    .sidenav{
        background: var(--dark);
        color: #fff;
        position: fixed;
        top: 0;
        bottom: 0;
        right: -100%;
        width: 300px;
        padding: 20px;
        transition: var(--transition);
        z-index: 10;
    }

    /********/
    .sidenav.show{
        right: 0;
    }
    /*************/
    .cancel-btn{
        position: absolute;
        right: 25px;
        font-size: 22px;
        cursor: pointer;
        transition: var(--transition);
    }
    .cancel-btn:hover{
        opacity: 0.7;
    }
    .navbar{
        margin-top: 50px;
        list-style: none;
        padding: 12px;
    }
    .navbar li a{
        color: #fff;
        text-transform: capitalize;
        text-decoration: none;
        padding: 15px 0;
        display: block;
        border-bottom: 0.5px solid rgba(249, 211, 66, 0.3);
        opacity: 0.8;
        letter-spacing: 1.5px;
        transition: var(--transition);
    }
    .navbar li a:hover{
        padding-left: 12px;
    }
    .sign-up, .log-in{
        background: var(--yellow);
        color: #fff;
    }
    @media(max-width: 400px){
        .sidenav{
            width: 100vw;
        }
    }

    {% block style %} {% endblock %}
  </style>
  {% block head %} {% endblock %}
</head>
<body>
  <!-- header -->
  <header class = "header" id = "header">
    <div class = "head-top">
        <div class = "site-name">
            <span><a href="{% url 'system:homepage' %}" style="text-decoration: none; color: white;">Home</a></span>
        </div>
        <div class = "site-nav">
            <span id = "nav-btn">MENU <i class = "fas fa-bars"></i></span>
        </div>
    </div>

  </header>
<!-- end of header -->

<!-- side navbar -->
<div class = "sidenav" id = "sidenav">
  <span class = "cancel-btn" id = "cancel-btn">
      <i class = "fas fa-times"></i>
  </span>

  <ul class = "navbar">
      <li><a href = "{% url 'system:homepage' %}" style="text-decoration: none; color: white;">Book Your Stay</a></li>
      <li><a href = "#rooms">Lorem ipsum</a></li><br>
      {% if user.is_authenticated %}
      <li><a href = "#customers">Booking List</a></li>
      {% endif %}
  </ul>
  {% if user.is_authenticated %}
  <button class = "btn1 log-in" style="margin-top: 50px;">Log Out</button>
  {% else %}
  <button class = "btn1 sign-up" style="margin-top: 20px;">Log In</button>
  {% endif %}
</div>
<!-- end of side navbar -->

<!-- fullscreen modal -->
<div id = "modal"></div>
<!-- end of fullscreen modal -->
  

  {% block content %}

  {% endblock %}

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
  <script>
    const navBtn = document.getElementById('nav-btn');
    const cancelBtn = document.getElementById('cancel-btn');
    const sideNav = document.getElementById('sidenav');
    const modal = document.getElementById('modal');
  
    navBtn.addEventListener("click", function(){
        sideNav.classList.add('show');
        modal.classList.add('showModal');
    });
  
    cancelBtn.addEventListener('click', function(){
        sideNav.classList.remove('show');
        modal.classList.remove('showModal');
    });
  
    window.addEventListener('click', function(event){
        if(event.target === modal){
            sideNav.classList.remove('show');
            modal.classList.remove('showModal');
        }
    });
  </script>
</body>
</html>

system/templates/system/book.html
{% extends 'system/base.html' %}
{% load static %}

{% block tittle %} Book Your Stay {% endblock %}

{% block head %} <link rel="stylesheet" href="{% static 'system/book.css' %}"> {% endblock %}

{% block content %}
  <div class="bg"></div>

    <form id="booking-form" action="" method="POST">
    {% csrf_token %}
      <div class="login-wrap">
        <div class="login-html">
          <input id="tab-1" type="radio" name="tab" class="sign-in" checked><label for="tab-1" class="tab" style="font-family: Century Gothic;">{{ category }}</label>
          <input id="tab-2" type="radio" name="tab" class="sign-up"><label for="tab-2" class="tab"></label>
          <div class="login-form">
            <div class="sign-in-htm">
                <div class="group">
                  <!-- <label for="id_che" class="label"></label> -->
                  <input type="hidden" name="category" id="id_category" class="input" value="{{ cat }}">
                </div>
                <div class="group">
                    <label for="id_check_in" class="label">Check In</label>
                    <input type="datetime-local" name="check_in" id="id_check_in" class="input">
                </div>
                <div class="group">
                    <label for="id_check_out" class="label">Check Out</label>
                    <input type="datetime-local" name="check_out" id="id_check_out" class="input">
                </div>
                <div class="group">
                    <label for="id_people" class="label">People</label>
                    <input type="number" name="people" id="id_people" class="input">
                </div>
                <!-- <div class="groeup">
                    <label for="id_room_category" class="label">Room Category :</label>
                    <select name="room_category" id="id_room_category" class="select">
                    <option value="STD" style="color: black; font-family: Century Gothic;">Standard</option>
                    <option value="CR" style="color: black; font-family: Century Gothic;">Connecting Room</option>
                    <option value="DEL" style="color: black; font-family: Century Gothic;">Deluxe</option>
                    <option value="KIN" style="color: black; font-family: Century Gothic;">King</option>
                    <option value="QUE" style="color: black; font-family: Century Gothic;">Queen</option>
                    <option value="SUI" style="color: black; font-family: Century Gothic;">Suite</option>
                    <option value="PEN" style="color: black; font-family: Century Gothic;">Penthouse</option>
                </select>
                </div> -->
                <div class="group">
                    <button type="submit" class="button" style="font-family: Century Gothic;">Book</button>
                </div>
                <div class="hr"></div>
                {% if user.is_authenticated %}
                <div class="foot-lnk">
                    <a href="{% url 'system:BookingList' %}" style="color: white; font-weight: 700; text-decoration: none;">Your Bookings</a>
                </div>
                {% else %}
                <div class="foot-lnk">
                    <a href="http://127.0.0.1:8000/accounts/login/" style="color: black;">Sign In</a>
                </div>
                {% endif %}
            </div>
          </div>
        </div>
      </div>
    </form>

{% endblock %}

system/templates/system/booking_cancel_view.html
{% extends 'system/base.html' %}
{% load static %}

{% block tittle %} Cancel Booking {% endblock %}
{% block head %}<link rel="stylesheet" href="{% static 'system/booking.css' %}">{% endblock %}

{% block content %}

<div class="header">
  <div class="headings" style="margin-top: 30px; display: flex; flex-direction: column; font-family: Century Gothic;">
      <h1 style="display: flex; justify-content: center; font-size: 2.7rem; color: azure;">Are You Sure you Wanna Cancel Your Booking ?</h1>
  </div>
</div>

<div class="screenwrapper">
  <div class="container">
    <div class="card">
      <div class="box">
        <div class="content">
          <h2>{{booking.room.number}}</h2>
          <h3>{{ booking.room.room_category }}</h3>
          <p>From: {{booking.check_in}} <br>To: {{booking.check_out}} <br><br> People : {{booking.room.people}}</p>
          <form id="booking-form" action="" method="POST">

            {% csrf_token %}
            <div class="input-div">
                <button type="submit" style="background: red; padding: 8px 20px; border-radius: 5px; 
                color: white; margin-top: 20px; box-shadow: 0 10px 20px rgba(0, 0, 0, 0.2); transition: 0.5s;">Confirm</button>
            </div>

          </form>
        </div>
      </div>
    </div>
  </div>
</div>
            
{% endblock %}

system/templates/system/bookings.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> Glug </title>
</head>
<body>

</body>
</html>

system/templates/system/room_list.html
{% extends 'system/base.html' %}
{% load static %}

{% block tittle %} Room List {% endblock %}
{% block style %}
body{
      background-image: linear-gradient(rgba(0,0,0,0.75), rgba(0,0,0,0.75)), url({% static 'system/Santorini-Sunset.jpg.optimal.jpg' %});
      background-position: center;
      background-size: cover;
    }
    html{
      scroll-behavior: smooth;
    }
    .screenwrapper{
      padding-top: 50px;
      width: 95vw;
      display: flex;
      flex-wrap: wrap;
      justify-content: center;
      align-items: center;
      overflow-x: hidden;
    }
    .card{
      margin: 10px 25px;
      margin-bottom: 30px;
    }
    .card:nth-child(odd) .card-body{
      background-color: rgba(0, 0, 0, 0.829);
    }
    .card:nth-child(odd) .card-body .btn{
      background-color: #14b6d3;
    }
    .card:nth-child(even) .card-body{
      background-color: #14b6d3;
    }
    .card:nth-child(even) .card-body .btn{
      background-color: rgba(0, 0, 0, 0.829);
    }
    p{
      font-weight: 300;
    }
    span{
      font-weight: 500;
    }
{% endblock %}

{% block content %}
    <div class="screenwrapper">
        {% for cat, cat_url in cat_list  %}
            <div class="card" style="width: 18rem;">
              <img src="{{ cat.category_picture.url }}" width="280" height="191" class="card-img-top" alt="...">
              <div class="card-body" style="color: azure;">
                <h5 class="card-title">{{ cat }}</h5>
                <p class="card-text">Lorem ipsum dolor sit amet consectetur, adipisicing elit.<br><br>
                <span>Actual Prize : <span style="text-decoration:  2px solid line-through crimson;">{{ cat.actual_prize_range }}</span> <br> Offered Prize : {{ cat.offer_prize_range }}</span></p>
                <a href="{{ cat_url }}" class="btn btn-primary d-flex justify-content-center">Explore Rooms</a>
              </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}

system/templates/system/sights.html
{% extends 'system/base.html' %}

{% block tittle %} Sights {% endblock %}

{% block content %}


{% endblock %}